name = "sporblord/typecollect"
version = "0.3.0"
description = "Exports the types from a set of Luau files into a single file."
authors = ["thalorum"]
license = "MIT"

includes = ["LICENSE", "README.md", "pesde.toml"]

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
