name = "sporblord/typecollect"
version = "0.4.0"
description = "Exports the types from a set of Luau files into a single file."
authors = ["sporblord"]
license = "MIT"

includes = ["LICENSE", "README.md", "pesde.toml", "src/files.luau"]

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
